"""
merge_city_geodata.py
Reads city_locations.csv and city_aliases.csv, writes js/city_data.js.

CITY_DATA:    refName → [minLon, minLat, maxLon, maxLat, fromYear?, toYear?]
              Bounding box is ±0.5° around the city point → zoom ~359.

CITY_ALIASES: historicalName → { key: refName, from: year, to: year }
              Used by vibeFindAllMatches to resolve historical names to city locations.
"""

import os, csv

MAPPER_DIR     = os.path.dirname(os.path.abspath(__file__))
LOC_CSV        = os.path.join(MAPPER_DIR, 'city_locations.csv')
ALIAS_CSV      = os.path.join(MAPPER_DIR, 'city_aliases.csv')
OVERRIDES_CSV  = os.path.join(MAPPER_DIR, 'city_overrides.csv')
OUT_JS         = os.path.join(MAPPER_DIR, 'js', 'city_data.js')

HALF = 0.5   # ±0.5° → zoom ~359


def parse_year(s):
    s = s.strip()
    if not s:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def js_key(name):
    return name.lower().replace("'", "\\'")


def fmt(v):
    return str(int(v)) if v == int(v) else f"{v:.6f}".rstrip('0')


# Load overrides: keyed by (lon_4dp, lat_4dp, from_year)
overrides = {}
if os.path.exists(OVERRIDES_CSV):
    with open(OVERRIDES_CSV, encoding='utf-8', newline='') as f:
        for row in csv.DictReader(f):
            key = (round(float(row['Lon']), 4), round(float(row['Lat']), 4), row['FromYear'].strip())
            overrides[key] = {'action': row['Action'].strip(), 'new_name': row['NewRefName'].strip()}
    print(f"Loaded {len(overrides)} city overrides")


def apply_override(row):
    """Returns (keep, new_row). keep=False means skip this row."""
    key = (round(float(row['Lon']), 4), round(float(row['Lat']), 4), row['FromYear'].strip())
    ov = overrides.get(key)
    if not ov:
        return True, row
    if ov['action'] in ('SKIP', 'SKIP_DUPE'):
        return False, row
    if ov['action'] == 'RENAME' and ov['new_name']:
        row = dict(row)
        row['RefName'] = ov['new_name']
    return True, row


locations = []
skipped_loc = 0
with open(LOC_CSV, encoding='utf-8', newline='') as f:
    for row in csv.DictReader(f):
        keep, row = apply_override(row)
        if keep:
            locations.append(row)
        else:
            skipped_loc += 1
if skipped_loc:
    print(f"Overrides: skipped {skipped_loc} location rows")

# Aliases now include Lon/Lat so we can apply the same coordinate-based overrides
aliases = []
skipped_alias = 0
with open(ALIAS_CSV, encoding='utf-8', newline='') as f:
    for row in csv.DictReader(f):
        # Use the alias row's own Lon/Lat for override lookup
        keep, row = apply_override(row)
        if keep:
            aliases.append(row)
        else:
            skipped_alias += 1
if skipped_alias:
    print(f"Overrides: skipped {skipped_alias} alias rows")

lines = [
    '// city_data.js — City locations and historical name aliases',
    '// Generated by merge_city_geodata.py — edit city_locations.csv / city_aliases.csv instead',
    '',
    'const CITY_DATA = {',
]

for loc in sorted(locations, key=lambda r: r['RefName'].lower()):
    lon = float(loc['Lon'])
    lat = float(loc['Lat'])
    min_lon = round(lon - HALF, 6)
    min_lat = round(lat - HALF, 6)
    max_lon = round(lon + HALF, 6)
    max_lat = round(lat + HALF, 6)

    from_yr = parse_year(loc['FromYear'])
    to_yr   = parse_year(loc['ToYear'])

    key = js_key(loc['RefName'])

    if from_yr is not None and to_yr is not None:
        arr = f"[{fmt(min_lon)}, {fmt(min_lat)}, {fmt(max_lon)}, {fmt(max_lat)}, {from_yr}, {to_yr}]"
    elif from_yr is not None:
        arr = f"[{fmt(min_lon)}, {fmt(min_lat)}, {fmt(max_lon)}, {fmt(max_lat)}, {from_yr}]"
    else:
        arr = f"[{fmt(min_lon)}, {fmt(min_lat)}, {fmt(max_lon)}, {fmt(max_lat)}]"

    lines.append(f"    '{key}': {arr},")

lines += ['};', '', 'const CITY_ALIASES = {']

# CITY_ALIASES: historical names only (IsRef != '1'), for vibe search
non_ref_aliases = [a for a in aliases if a.get('IsRef', '0') != '1']
for alias in sorted(non_ref_aliases, key=lambda r: r['AliasName'].lower()):
    alias_key = js_key(alias['AliasName'])
    ref_key   = js_key(alias['RefName'])
    from_yr   = parse_year(alias['FromYear'])
    to_yr     = parse_year(alias['ToYear'])
    from_str  = str(from_yr) if from_yr is not None else 'null'
    to_str    = str(to_yr)   if to_yr   is not None else 'null'
    lines.append(f"    '{alias_key}': {{ key: '{ref_key}', from: {from_str}, to: {to_str} }},")

# CITY_HISTORY: all names (including ref) grouped by ref key, for popups
from collections import defaultdict
history = defaultdict(list)
for alias in aliases:
    ref_key  = js_key(alias['RefName'])
    from_yr  = parse_year(alias['FromYear'])
    to_yr    = parse_year(alias['ToYear'])
    history[ref_key].append({
        'name': alias['AliasName'],
        'from': from_yr,
        'to':   to_yr,
    })

lines += ['};', '', 'const CITY_HISTORY = {']
for ref_key in sorted(history.keys()):
    entries = sorted(history[ref_key], key=lambda e: (e['from'] is None, e['from'] or 0))
    parts = []
    for e in entries:
        from_str = str(e['from']) if e['from'] is not None else 'null'
        to_str   = str(e['to'])   if e['to']   is not None else 'null'
        parts.append(f"{{ name: '{e['name'].replace(chr(39), chr(92)+chr(39))}', from: {from_str}, to: {to_str} }}")
    lines.append(f"    '{ref_key}': [{', '.join(parts)}],")

lines += ['};', '']

with open(OUT_JS, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Wrote {len(locations)} city entries, {len(non_ref_aliases)} aliases, and {len(history)} history entries to {OUT_JS}")
