"""
merge_city_geodata.py
Reads city_locations.csv and city_aliases.csv, writes js/city_data.js.

CITY_DATA:    refName → [minLon, minLat, maxLon, maxLat, fromYear?, toYear?]
              Bounding box is ±0.5° around the city point → zoom ~359.

CITY_ALIASES: historicalName → { key: refName, from: year, to: year }
              Used by vibeFindAllMatches to resolve historical names to city locations.
"""

import os, csv

MAPPER_DIR = os.path.dirname(os.path.abspath(__file__))
LOC_CSV    = os.path.join(MAPPER_DIR, 'city_locations.csv')
ALIAS_CSV  = os.path.join(MAPPER_DIR, 'city_aliases.csv')
OUT_JS     = os.path.join(MAPPER_DIR, 'js', 'city_data.js')

HALF = 0.5   # ±0.5° → zoom ~359


def parse_year(s):
    s = s.strip()
    if not s:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def js_key(name):
    return name.lower().replace("'", "\\'")


def fmt(v):
    return str(int(v)) if v == int(v) else f"{v:.6f}".rstrip('0')


locations = []
with open(LOC_CSV, encoding='utf-8', newline='') as f:
    for row in csv.DictReader(f):
        locations.append(row)

aliases = []
with open(ALIAS_CSV, encoding='utf-8', newline='') as f:
    for row in csv.DictReader(f):
        aliases.append(row)

lines = [
    '// city_data.js — City locations and historical name aliases',
    '// Generated by merge_city_geodata.py — edit city_locations.csv / city_aliases.csv instead',
    '',
    'const CITY_DATA = {',
]

for loc in sorted(locations, key=lambda r: r['RefName'].lower()):
    lon = float(loc['Lon'])
    lat = float(loc['Lat'])
    min_lon = round(lon - HALF, 6)
    min_lat = round(lat - HALF, 6)
    max_lon = round(lon + HALF, 6)
    max_lat = round(lat + HALF, 6)

    from_yr = parse_year(loc['FromYear'])
    to_yr   = parse_year(loc['ToYear'])

    key = js_key(loc['RefName'])

    if from_yr is not None and to_yr is not None:
        arr = f"[{fmt(min_lon)}, {fmt(min_lat)}, {fmt(max_lon)}, {fmt(max_lat)}, {from_yr}, {to_yr}]"
    elif from_yr is not None:
        arr = f"[{fmt(min_lon)}, {fmt(min_lat)}, {fmt(max_lon)}, {fmt(max_lat)}, {from_yr}]"
    else:
        arr = f"[{fmt(min_lon)}, {fmt(min_lat)}, {fmt(max_lon)}, {fmt(max_lat)}]"

    lines.append(f"    '{key}': {arr},")

lines += ['};', '', 'const CITY_ALIASES = {']

for alias in sorted(aliases, key=lambda r: r['AliasName'].lower()):
    alias_key = js_key(alias['AliasName'])
    ref_key   = js_key(alias['RefName'])
    from_yr   = parse_year(alias['FromYear'])
    to_yr     = parse_year(alias['ToYear'])

    from_str = str(from_yr) if from_yr is not None else 'null'
    to_str   = str(to_yr)   if to_yr   is not None else 'null'

    lines.append(f"    '{alias_key}': {{ key: '{ref_key}', from: {from_str}, to: {to_str} }},")

lines += ['};', '']

with open(OUT_JS, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Wrote {len(locations)} city entries and {len(aliases)} aliases to {OUT_JS}")
